[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  # Skip TypeScript type checking during build for faster builds
  NETLIFY_SKIP_TS_CHECK = "true"
  # Set ESLint to not fail on errors
  ESLINT_NO_DEV_ERRORS = "true"
  NEXT_DISABLE_ESLINT = "true"
  
[build.processing]
  skip_processing = true

# Ensure Next.js specific build steps
[[plugins]]
  package = "@netlify/plugin-nextjs" 